### PR TITLE
Support "work in progress" label

### LINKED ISSUE #57: Support labels
To keep PR titles cleaner, we use labels. Could we add configuration for this?

### PR DESCRIPTION
**Pull request by jbrooksuk**
Closes #57

### CODE REVIEW

**Comment by sa-jepstein** [comment]
Could you please update the [`README.md`](https://github.com/gr2m/wip-bot/blob/master/README.md) as well under "Usage" so it stays up to date?

**Comment by jbrooksuk** [comment]
All done.

**Comment by sa-jepstein** [comment]
@gr2m Thank you as well! Can you update the description in https://github.com/apps/wip with this new search query?

**Comment by gr2m** [comment]
> Can you update the description in https://github.com/apps/wip with this new search query?

Ha! Good catch! I’d love it if we could automate that 🤔

**Pull request merged**
