### PR TITLE
Updated Node.js engine and npm to recent version

### PR DESCRIPTION
**Pull request by aps120797**

### CODE REVIEW

**Comment by aps120797** [comment]
Updated. 😄 
Tested by deploying on Glitch. Works fine there.

**Comment by gr2m** [comment]
Can you please try to deploy to now.sh?

**Comment by aps120797** [comment]
@gr2m , I deployed it on now.sh using [now-cli](https://github.com/zeit/now-cli). And, it's deployment is working fine. [See screenshot]
Note that by updating package.json by using `>=`, with this, it's updating Node.js to version `9.10.1`, (most recent stable version with latest features).
```
"engines": {
    "node": ">=8.3.0",
    "npm": ">=5.3.0"
  },
```
And by just using the old statement, it's updating it to Node.js version 8.11.1 (most recent version of Node.js version 8).
```
"engines": {
    "node": "8",
  },
```

capture

**Pull request merged**
