### PR TITLE
refactor: Destructure PR number from payload

### LINKED ISSUE #38: Destructure PR number for use
Get number from - https://github.com/gr2m/wip-bot/blob/6d67f35f4168338a82b91885e16459e6aaf3df8c/lib/handle-pull-request-change.js#L4

Use in - 
https://github.com/gr2m/wip-bot/blob/6d67f35f4168338a82b91885e16459e6aaf3df8c/lib/handle-pull-request-change.js#L21

Lemme know if we need this @gr2m

### PR DESCRIPTION
**Pull request by anshumanv**
Fixes #38

### CODE REVIEW

**Comment by anshumanv** [comment]
Will just a `context.repo({ number })` work?

**Comment by anshumanv** [comment]
Why does travis say `number` is not in use when it is. :worried:

**Comment by anshumanv** [comment]
Oh, destructuring is done in `handlePullRequestChange` function and I think from there it is not accessible in `commitContainsWIP` :worried:

**Comment by gr2m** [comment]
> Oh, destructuring is done in `handlePullRequestChange` function and I think from there it is not accessible in `commitContainsWIP` :worried: 

ahh I'm sorry, I missed that, too. I fear we better leave it as is then? We could also pass `number` as 2nd argument to `commitsContainWIP` but I don’t think that makes the code any more readable ... what do you think?

**Comment by anshumanv** [comment]
Yes, let's leave it as is, passing a 2nd argument will only make it complex. :+1: 
I absolutely missed it too. :sweat_smile:

**Pull request closed without merging**
